### ISSUE TITLE
get_template_files is not returning URL

### ISSUE THREAD

**Issue by kevteg** [HelloFax/hellosign-python-sdk-demo#2]
Hi, I needed to use the `get_templates_files` method to retrieve the document URL, but it doesn't have the `get_url` param defined.

https://app.hellosign.com/api/reference#get_template_files

**Comment by kevteg** [comment]
Sorry I didn't realize I open the issue in the demo.

**Comment by jyoung488** [comment]
@kevteg If you're running into any issues, please feel free to write into apisupport@hellosign.com with your questions. Thank you!
